-- Replace all previous coursework/homework with the new 3-module, 24-session set.
-- This creates 4 global tasks per session:
--   2 Class Challenges + 2 Home Tasks
-- Global tasks use batch_id = null and assigned_student_id = null, so every student can see them.
--
-- WARNING: deleting homework cascades to submissions and submission_evidence for those old tasks.

begin;

delete from public.homework;

with coursework(module_order, session_number, session_title, what_students_learn, tools, ai_type, resource_type, file_name, google_doc_link) as (
  values
    (1, 1, 'Welcome to the AI Era', 'Students learn what AI is, what it can do, what it cannot do, prompt engineering fundamentals, role prompting, and chain-of-thought style reasoning.', 'ChatGPT, Claude, Gemini', 'AI Literacy & Prompt Engineering', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1nyybUpzX2aHGuHzp2CBXUk1ypLQSKhlW3xcfKK_aHAM/edit?usp=drivesdk'),
    (1, 1, 'Welcome to the AI Era', 'Students learn what AI is, what it can do, what it cannot do, prompt engineering fundamentals, role prompting, and chain-of-thought style reasoning.', 'ChatGPT, Claude, Gemini', 'AI Literacy & Prompt Engineering', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1knunxrtJ7HzzOW6iRpNqkR_Yofplwwg4t3BxpcDF8sE/edit?usp=drivesdk'),
    (1, 1, 'Welcome to the AI Era', 'Students learn what AI is, what it can do, what it cannot do, prompt engineering fundamentals, role prompting, and chain-of-thought style reasoning.', 'ChatGPT, Claude, Gemini', 'AI Literacy & Prompt Engineering', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1bpUDZjG060j51lhHPVvCHWZP2IW-fOVNJikCFwLKVlw/edit?usp=drivesdk'),
    (1, 1, 'Welcome to the AI Era', 'Students learn what AI is, what it can do, what it cannot do, prompt engineering fundamentals, role prompting, and chain-of-thought style reasoning.', 'ChatGPT, Claude, Gemini', 'AI Literacy & Prompt Engineering', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1SZ_eQLMGfKe5_vhmFfVfSK1IvhjbkbnMkovIkaYTkZs/edit?usp=drivesdk'),
    (1, 2, 'AI for School: Study Smarter', 'Students use AI to create study guides, explain complex topics, generate practice questions, summarize textbook chapters, create flashcards, and build a complete study system for one real school subject.', 'Gemini, NotebookLM', 'Practical AI', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1UmeP8tnpIklvEHE7lCF-COwL0ju7A0S0ptipd0t7UXQ/edit?usp=drivesdk'),
    (1, 2, 'AI for School: Study Smarter', 'Students use AI to create study guides, explain complex topics, generate practice questions, summarize textbook chapters, create flashcards, and build a complete study system for one real school subject.', 'Gemini, NotebookLM', 'Practical AI', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1b9xmAMBVsq4nlCIztboSc72wcexGzbZXmQ3_Y2CGP68/edit?usp=drivesdk'),
    (1, 2, 'AI for School: Study Smarter', 'Students use AI to create study guides, explain complex topics, generate practice questions, summarize textbook chapters, create flashcards, and build a complete study system for one real school subject.', 'Gemini, NotebookLM', 'Practical AI', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1hIEmdF70cOONCPSuTp2NTIMaJt6YV4EZ6RunArW2k38/edit?usp=drivesdk'),
    (1, 2, 'AI for School: Study Smarter', 'Students use AI to create study guides, explain complex topics, generate practice questions, summarize textbook chapters, create flashcards, and build a complete study system for one real school subject.', 'Gemini, NotebookLM', 'Practical AI', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1kITBYC3qGvRqDFjKdBjfFG4HWfp6dGhNThyrKE8jGho/edit?usp=drivesdk'),
    (1, 3, 'AI for Creative Writing', 'Students use AI as a writing partner to brainstorm, outline, draft, edit, and improve a blog post, essay, or story.', 'QuillBot, ZeroGPT, WrizzleAI', 'Content / Creative Writing', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1xmNVyiuguxO_B6TgZ0RIgD8w7Uo26ss4kwBvZa30bUY/edit?usp=drivesdk'),
    (1, 3, 'AI for Creative Writing', 'Students use AI as a writing partner to brainstorm, outline, draft, edit, and improve a blog post, essay, or story.', 'QuillBot, ZeroGPT, WrizzleAI', 'Content / Creative Writing', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/13CTwe5Dd6nKHYVACeKWuROP0TkSwmySS7AJWPvH3tZQ/edit?usp=drivesdk'),
    (1, 3, 'AI for Creative Writing', 'Students use AI as a writing partner to brainstorm, outline, draft, edit, and improve a blog post, essay, or story.', 'QuillBot, ZeroGPT, WrizzleAI', 'Content / Creative Writing', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1lSMBKKBQxwAw-EoW_5cTkOVWX3ZRoiKfADByEK6mWkU/edit?usp=drivesdk'),
    (1, 3, 'AI for Creative Writing', 'Students use AI as a writing partner to brainstorm, outline, draft, edit, and improve a blog post, essay, or story.', 'QuillBot, ZeroGPT, WrizzleAI', 'Content / Creative Writing', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1LuNk95-T6tusEbkOgqw7AE4NSQw5CaBKVcTe7VC23pk/edit?usp=drivesdk'),
    (1, 4, 'AI Image & Video Creation', 'Students explore AI image generation, create social media graphics and concept art, and discuss AI art ethics, copyright, and deepfakes.', 'Gemini, Canva AI, MidJourney', 'Creative AI', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1P6AHeokYGv2HZdJ6-8qB7tL-X9Eqm5aKz-yyzcutcC0/edit?usp=drivesdk'),
    (1, 4, 'AI Image & Video Creation', 'Students explore AI image generation, create social media graphics and concept art, and discuss AI art ethics, copyright, and deepfakes.', 'Gemini, Canva AI, MidJourney', 'Creative AI', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1ClYT2-9Pd47OQjXAFxLxyn_oUu49EFYoi33CXYypOj4/edit?usp=drivesdk'),
    (1, 4, 'AI Image & Video Creation', 'Students explore AI image generation, create social media graphics and concept art, and discuss AI art ethics, copyright, and deepfakes.', 'Gemini, Canva AI, MidJourney', 'Creative AI', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1IBWck7O-2UB1NLIGfBSoSzjJv7DcDm-6PIEZAAMKiiM/edit?usp=drivesdk'),
    (1, 4, 'AI Image & Video Creation', 'Students explore AI image generation, create social media graphics and concept art, and discuss AI art ethics, copyright, and deepfakes.', 'Gemini, Canva AI, MidJourney', 'Creative AI', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/11iXkCPWf4Y583x53y_aBEat9gQ5ZSXhhAiOor0iLJfo/edit?usp=drivesdk'),
    (1, 5, 'AI Audio Generation', 'Students explore AI-generated music, voice, and sound effects, then create audio assets for podcasts, games, storytelling, or creative projects.', 'Suno AI, ElevenLabs, Udio', 'Creative AI', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1CI8JhpEBbwUZrQBuS-O1vo9tcNYiHjCfQSqkQodFwx4/edit?usp=drivesdk'),
    (1, 5, 'AI Audio Generation', 'Students explore AI-generated music, voice, and sound effects, then create audio assets for podcasts, games, storytelling, or creative projects.', 'Suno AI, ElevenLabs, Udio', 'Creative AI', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1WEw3OfEapfEoEEvtiw4em3IDmKeePadRG4KkqT4PBqI/edit?usp=drivesdk'),
    (1, 5, 'AI Audio Generation', 'Students explore AI-generated music, voice, and sound effects, then create audio assets for podcasts, games, storytelling, or creative projects.', 'Suno AI, ElevenLabs, Udio', 'Creative AI', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1MAEmEzr6Vi1XgX0_iOWigK3vpNVhhpB0av9tUeY8_2U/edit?usp=drivesdk'),
    (1, 5, 'AI Audio Generation', 'Students explore AI-generated music, voice, and sound effects, then create audio assets for podcasts, games, storytelling, or creative projects.', 'Suno AI, ElevenLabs, Udio', 'Creative AI', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1QVi4tBODsRVhrzccHdS_zfQ9dzNQM8WBsdCD8snLSlM/edit?usp=drivesdk'),
    (1, 6, 'AI for Task Organisation - The Data Analyst', 'Students organize tasks, notes, and information using AI, analyze simple datasets, create task plans, and generate insights from schedules, projects, or habit data.', 'Notion AI, Claude, OpenAI', 'Smart Data AI', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1hwBPXGrp0QsK9Zu7lPf50NBbXZs6cS7jcBhFh6O5rKo/edit?usp=drivesdk'),
    (1, 6, 'AI for Task Organisation - The Data Analyst', 'Students organize tasks, notes, and information using AI, analyze simple datasets, create task plans, and generate insights from schedules, projects, or habit data.', 'Notion AI, Claude, OpenAI', 'Smart Data AI', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1wWaf3W8e20irCWGaSolsjnKryPhowgyE0h7qLlH-8Ms/edit?usp=drivesdk'),
    (1, 6, 'AI for Task Organisation - The Data Analyst', 'Students organize tasks, notes, and information using AI, analyze simple datasets, create task plans, and generate insights from schedules, projects, or habit data.', 'Notion AI, Claude, OpenAI', 'Smart Data AI', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1Sx5X_J7VhJe1Z2MJi3k0OSUMqDJxTWaCTWR2y5CoQWA/edit?usp=drivesdk'),
    (1, 6, 'AI for Task Organisation - The Data Analyst', 'Students organize tasks, notes, and information using AI, analyze simple datasets, create task plans, and generate insights from schedules, projects, or habit data.', 'Notion AI, Claude, OpenAI', 'Smart Data AI', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1dkjyCS-MS5IqXxNW9Xqa1BhVJpUEQEElULCIsqLDv2g/edit?usp=drivesdk'),
    (1, 7, 'AI without Internet - Going Local', 'Students learn how to run AI without internet access, organize local tasks, and use a local version of their project.', 'Ollama, LM Studio, Gemma', 'Local AI / Offline AI Systems', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1ZNbwp2iI9n915WB7QnUEYt_Bu19Okbb5JISeBp9vmRs/edit?usp=drivesdk'),
    (1, 7, 'AI without Internet - Going Local', 'Students learn how to run AI without internet access, organize local tasks, and use a local version of their project.', 'Ollama, LM Studio, Gemma', 'Local AI / Offline AI Systems', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1lf0DJXPRSEUcZWJ92Hl5J7F0i9Q-O-jv-tUv1Mc56VM/edit?usp=drivesdk'),
    (1, 7, 'AI without Internet - Going Local', 'Students learn how to run AI without internet access, organize local tasks, and use a local version of their project.', 'Ollama, LM Studio, Gemma', 'Local AI / Offline AI Systems', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1G9JZKiqDGVCgKvVfHAtgyFikcBWcPtvYXy4hyr4SNRw/edit?usp=drivesdk'),
    (1, 7, 'AI without Internet - Going Local', 'Students learn how to run AI without internet access, organize local tasks, and use a local version of their project.', 'Ollama, LM Studio, Gemma', 'Local AI / Offline AI Systems', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1GuujEpkXBk1Bvb8JENvYsqhp1JlW0HfQU2KvOUJnxBw/edit?usp=drivesdk'),
    (1, 8, 'AI Presentations: Pitch Like a Pro / Showcase Session', 'Students create and present an AI-powered presentation showcasing their learning journey and projects from the module.', 'Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1x846jq3KwMNBzWf7D5WtH9iwQC3TOMNmSeyXBeLEYNg/edit?usp=drivesdk'),
    (1, 8, 'AI Presentations: Pitch Like a Pro / Showcase Session', 'Students create and present an AI-powered presentation showcasing their learning journey and projects from the module.', 'Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1QKhSYjjFgv9QFeMi2sbEi2bEa3TY3BaYgGLoB8CtHE4/edit?usp=drivesdk'),
    (1, 8, 'AI Presentations: Pitch Like a Pro / Showcase Session', 'Students create and present an AI-powered presentation showcasing their learning journey and projects from the module.', 'Gamma', 'AI Productivity', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1mqP1XLuDW96FwndPUJiWa4sPgCyz4UkY7aRMmOGLNWE/edit?usp=drivesdk'),
    (1, 8, 'AI Presentations: Pitch Like a Pro / Showcase Session', 'Students create and present an AI-powered presentation showcasing their learning journey and projects from the module.', 'Gamma', 'AI Productivity', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1WGXUWsOnYV9ghnZzxSvGpi1P68br-GFkK-wiuhNf9dw/edit?usp=drivesdk'),
    (2, 1, 'Vibe Coding: No-Code App Magic', 'Students learn how to build a simple app using AI prompts without writing code. They turn an idea into a working app and customize the generated interface.', 'Bolt.new', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1wsW4qVapwpSKJ5feoNdVIr8QJS_gp2S0sJYYszOVTBs/edit?usp=drivesdk'),
    (2, 1, 'Vibe Coding: No-Code App Magic', 'Students learn how to build a simple app using AI prompts without writing code. They turn an idea into a working app and customize the generated interface.', 'Bolt.new', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1JXlyPjzzTCSmFKPvZ0BKTFOqjMnoAzn2lZFG7tLPFVU/edit?usp=drivesdk'),
    (2, 1, 'Vibe Coding: No-Code App Magic', 'Students learn how to build a simple app using AI prompts without writing code. They turn an idea into a working app and customize the generated interface.', 'Bolt.new', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1kMUA3rNwy7pClLV7MqN8Q5_zFAsA4hMXzJojBURXlOI/edit?usp=drivesdk'),
    (2, 1, 'Vibe Coding: No-Code App Magic', 'Students learn how to build a simple app using AI prompts without writing code. They turn an idea into a working app and customize the generated interface.', 'Bolt.new', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1ky21VT5qNuiCXOQOiqJV48iadHgYvq0JGJu70jVuImg/edit?usp=drivesdk'),
    (2, 2, 'Vibe Coding: From Idea to App', 'Students build production-ready apps through conversation with AI agents that design, code, and deploy applications from start to finish.', 'Emergent.sh', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1qSXoWw-E3Pe6HBy9Hk2Qe9I0u4P6tOr9tIRauHylLcE/edit?usp=drivesdk'),
    (2, 2, 'Vibe Coding: From Idea to App', 'Students build production-ready apps through conversation with AI agents that design, code, and deploy applications from start to finish.', 'Emergent.sh', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1jVmIDE1OzoIe7VWBeGBXUYyK5k_q3IwMlAozFSKhSl8/edit?usp=drivesdk'),
    (2, 2, 'Vibe Coding: From Idea to App', 'Students build production-ready apps through conversation with AI agents that design, code, and deploy applications from start to finish.', 'Emergent.sh', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1dHikT1GnAqdplMEHAozInlg1T165RyeM9OGFRKb6aPk/edit?usp=drivesdk'),
    (2, 2, 'Vibe Coding: From Idea to App', 'Students build production-ready apps through conversation with AI agents that design, code, and deploy applications from start to finish.', 'Emergent.sh', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1i0X5gsksBfsFLf8ckeur4uwJBbw2Mh2LEPddC-Cm9Bs/edit?usp=drivesdk'),
    (2, 3, 'Figma AI Tools', 'Students design frontends using Figma AI tools, including AI design generation and Make features.', 'Figma AI', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1OJRlC_eZPdUGpJGSPxeYTTJFoPGwWAcQhSKP0-vemEo/edit?usp=drivesdk'),
    (2, 3, 'Figma AI Tools', 'Students design frontends using Figma AI tools, including AI design generation and Make features.', 'Figma AI', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1k5pjpSR9txxdRJc3c1gBEIhLAKoY6CO_m4qHuf0Nw7I/edit?usp=drivesdk'),
    (2, 3, 'Figma AI Tools', 'Students design frontends using Figma AI tools, including AI design generation and Make features.', 'Figma AI', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1pQJudRXGqMgCGwGa8v5Q-7mBYrQ1VUE22qOKWEfk1S4/edit?usp=drivesdk'),
    (2, 3, 'Figma AI Tools', 'Students design frontends using Figma AI tools, including AI design generation and Make features.', 'Figma AI', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1qiE3AyvZfamwNkonRnytdFVxcO6R1fc6rUo9L0PswHc/edit?usp=drivesdk'),
    (2, 4, 'No-Code GPT Wrappers', 'Students learn how to build GPT wrappers and AI-powered apps using no-code and AI-assisted tools.', 'OpenAI GPTs', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1gE8hjOZv6Ppai_n4NkNqea0BDm19D5MFlDYlixYJdto/edit?usp=drivesdk'),
    (2, 4, 'No-Code GPT Wrappers', 'Students learn how to build GPT wrappers and AI-powered apps using no-code and AI-assisted tools.', 'OpenAI GPTs', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1BSv3XpOcaOie8NknLpX-grMUu4w6FathluCJ-f3FH5I/edit?usp=drivesdk'),
    (2, 4, 'No-Code GPT Wrappers', 'Students learn how to build GPT wrappers and AI-powered apps using no-code and AI-assisted tools.', 'OpenAI GPTs', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1zYOlOS6DtwtGfRQh_zr5XuYicbX9e6mlJlPNnFeoMho/edit?usp=drivesdk'),
    (2, 4, 'No-Code GPT Wrappers', 'Students learn how to build GPT wrappers and AI-powered apps using no-code and AI-assisted tools.', 'OpenAI GPTs', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1CCVBJNggpa-UCiuskrjvP1b5wzKLdwZkFvy25XIvzag/edit?usp=drivesdk'),
    (2, 5, 'Google AI Studio: Gemini Playground / AntiGravity', 'Students explore Google AI Studio and Gemini Playground for hands-on AI experimentation and creative projects.', 'Google AI Studio', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1_UuTaQvHsZm1-fHTZf1nd-nwZS74gTq9mj9KHrhjxL0/edit?usp=drivesdk'),
    (2, 5, 'Google AI Studio: Gemini Playground / AntiGravity', 'Students explore Google AI Studio and Gemini Playground for hands-on AI experimentation and creative projects.', 'Google AI Studio', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1sIh00WzveIXge06XAA5XtKdmgUkQNcsUda11h7HIsWE/edit?usp=drivesdk'),
    (2, 5, 'Google AI Studio: Gemini Playground / AntiGravity', 'Students explore Google AI Studio and Gemini Playground for hands-on AI experimentation and creative projects.', 'Google AI Studio', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1hmKyuHCkLqPuwc9pbjRrCsQGj91nvDU-d0FyAiVb3yk/edit?usp=drivesdk'),
    (2, 5, 'Google AI Studio: Gemini Playground / AntiGravity', 'Students explore Google AI Studio and Gemini Playground for hands-on AI experimentation and creative projects.', 'Google AI Studio', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/10L30rnHE2aei6p_WdxUsmLzw0MTpzBAqzzPGPtXYOx8/edit?usp=drivesdk'),
    (2, 6, 'Exploring Google Labs', 'Students experiment with Google Labs tools and explore creative AI experiments.', 'Google Whisk.ai', 'Vibe Coding', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/138C4efNPkaPPixxcQ9_HlYMfmNc2pQutsOMmVeAsGfM/edit?usp=drivesdk'),
    (2, 6, 'Exploring Google Labs', 'Students experiment with Google Labs tools and explore creative AI experiments.', 'Google Whisk.ai', 'Vibe Coding', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1wwH4iuPqLpk_cT_ZN49h-rUFG4On3IudBZJgR3LUFNo/edit?usp=drivesdk'),
    (2, 6, 'Exploring Google Labs', 'Students experiment with Google Labs tools and explore creative AI experiments.', 'Google Whisk.ai', 'Vibe Coding', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1lMEunkbr6toKDRuDth-_v7NtinHbkgeTYDsTIknrNEY/edit?usp=drivesdk'),
    (2, 6, 'Exploring Google Labs', 'Students experiment with Google Labs tools and explore creative AI experiments.', 'Google Whisk.ai', 'Vibe Coding', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1w488lldY7RaOZ7GYoahiqfwpWL66BYOyHDoa1RSA75o/edit?usp=drivesdk'),
    (2, 7, 'AI Ethics & Responsibility', 'Students examine AI bias, misinformation, job displacement, privacy, deepfakes, AI disclosure, cheating concerns, regulation, and create an AI Ethics Code for their school.', 'Sensity AI, Hive AI', 'AI Ethics', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1zCy6tt4Kr9RN040kw1nnED_i2M5jC2p7mnlYnaeZgJ0/edit?usp=drivesdk'),
    (2, 7, 'AI Ethics & Responsibility', 'Students examine AI bias, misinformation, job displacement, privacy, deepfakes, AI disclosure, cheating concerns, regulation, and create an AI Ethics Code for their school.', 'Sensity AI, Hive AI', 'AI Ethics', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1V1JNHpH0UinPhRkhaWcUJTX4ubQz3kXM1_mp8KnshmA/edit?usp=drivesdk'),
    (2, 7, 'AI Ethics & Responsibility', 'Students examine AI bias, misinformation, job displacement, privacy, deepfakes, AI disclosure, cheating concerns, regulation, and create an AI Ethics Code for their school.', 'Sensity AI, Hive AI', 'AI Ethics', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1t3VfYFVqj6ytMci3BtIyLAuIM4Tl3aoAWPQSwtOHA8E/edit?usp=drivesdk'),
    (2, 7, 'AI Ethics & Responsibility', 'Students examine AI bias, misinformation, job displacement, privacy, deepfakes, AI disclosure, cheating concerns, regulation, and create an AI Ethics Code for their school.', 'Sensity AI, Hive AI', 'AI Ethics', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/180OaVdH-SGzlEytX72GNo4JU4w79k4udWTIK3M7_wjA/edit?usp=drivesdk'),
    (2, 8, 'Showcase Session - Present Your Smart AI App', 'Students present the AI-powered applications and projects they built throughout the module.', 'Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/148tt4npokwBQPQ-beGBIbJ-kww0kJpL5RZaXHrO_Gz0/edit?usp=drivesdk'),
    (2, 8, 'Showcase Session - Present Your Smart AI App', 'Students present the AI-powered applications and projects they built throughout the module.', 'Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1RCy82ybmyLKGFmPN7WnaRTV4ftHZx9ZRzv79BM96ACQ/edit?usp=drivesdk'),
    (2, 8, 'Showcase Session - Present Your Smart AI App', 'Students present the AI-powered applications and projects they built throughout the module.', 'Gamma', 'AI Productivity', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1eirAsZTPs72ldL6WgaG4_jobUMJI7YVMvCoIxDDBBfI/edit?usp=drivesdk'),
    (2, 8, 'Showcase Session - Present Your Smart AI App', 'Students present the AI-powered applications and projects they built throughout the module.', 'Gamma', 'AI Productivity', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/11wGKZSubmSUZgh8kMAR3T00FHf-gc8K1BT_dzO5Cp1s/edit?usp=drivesdk'),
    (3, 1, 'AI Agents and Tools', 'Students are introduced to AI agents and automation tools, including how AI agents work and the tools that power them.', 'AI Tools', 'AI Agents', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1CeLMvmwjI8W4QDa81eFctFhhwVzNBEFpRsiYEIB2_H4/edit?usp=drivesdk'),
    (3, 1, 'AI Agents and Tools', 'Students are introduced to AI agents and automation tools, including how AI agents work and the tools that power them.', 'AI Tools', 'AI Agents', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1JIgWkFXdlRqXVxg41wPCra1TRB-hIq-bQictKnfKEe8/edit?usp=drivesdk'),
    (3, 1, 'AI Agents and Tools', 'Students are introduced to AI agents and automation tools, including how AI agents work and the tools that power them.', 'AI Tools', 'AI Agents', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1sl4aR7DyCbNdxN8NvVHtsuBLOid4q0YlVywEq23XwsM/edit?usp=drivesdk'),
    (3, 1, 'AI Agents and Tools', 'Students are introduced to AI agents and automation tools, including how AI agents work and the tools that power them.', 'AI Tools', 'AI Agents', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1eVq6LiPcboukaM3dvsp9iYGjcVT8fGGt1Qq0xljuSCc/edit?usp=drivesdk'),
    (3, 2, 'Introduction to AI Automation', 'Students learn what automation is, why it matters, and see an example workflow that summarizes emails and posts updates automatically.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1Ixdv3qjaa0CXkWfLHvJVOxdk9S1oP0PZl2TeoWpjVpQ/edit?usp=drivesdk'),
    (3, 2, 'Introduction to AI Automation', 'Students learn what automation is, why it matters, and see an example workflow that summarizes emails and posts updates automatically.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1o3-PfSSKTXwjYdxIw7gaM58pFMT31waVfp62nc1qSsA/edit?usp=drivesdk'),
    (3, 2, 'Introduction to AI Automation', 'Students learn what automation is, why it matters, and see an example workflow that summarizes emails and posts updates automatically.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1mZLdOSn33Ef_zdJxpE6aS3r-B3SpoFvX_cdyvzJO3zc/edit?usp=drivesdk'),
    (3, 2, 'Introduction to AI Automation', 'Students learn what automation is, why it matters, and see an example workflow that summarizes emails and posts updates automatically.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1dbbQyFPnCpIZPSkYUw2_UwpmISCiz2Dc5L1xamF0ics/edit?usp=drivesdk'),
    (3, 3, 'Build Your First AI Workflow', 'Students build a simple n8n automation using triggers, AI processing, outputs, nodes, connections, and AI nodes.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1XJ5iCsa_hQrFtGPyc1tSj20aH0DrpciP4cAi6dMa_DI/edit?usp=drivesdk'),
    (3, 3, 'Build Your First AI Workflow', 'Students build a simple n8n automation using triggers, AI processing, outputs, nodes, connections, and AI nodes.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1WguzK_2jrbSBQKmm5NfeZ1IcslYbN41z3Mhmw9DurCk/edit?usp=drivesdk'),
    (3, 3, 'Build Your First AI Workflow', 'Students build a simple n8n automation using triggers, AI processing, outputs, nodes, connections, and AI nodes.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1NZib-hDYpS3BRMQ92L9eCFpIJxGUdLtn5zl0O8EL0SY/edit?usp=drivesdk'),
    (3, 3, 'Build Your First AI Workflow', 'Students build a simple n8n automation using triggers, AI processing, outputs, nodes, connections, and AI nodes.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1aiVN6BcB4r9h1IBq1NYMrGgxUjS7MIaCnw_0ft-SCks/edit?usp=drivesdk'),
    (3, 4, 'AI Workflow: Content Pipeline', 'Students build an advanced n8n content pipeline that turns a topic into a blog post, social caption, image alt text, and ready-to-publish content package.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1HURt1Fmh4NWCTJ5IgewDMu3rzg7V5NG6JVp7YMRdWjA/edit?usp=drivesdk'),
    (3, 4, 'AI Workflow: Content Pipeline', 'Students build an advanced n8n content pipeline that turns a topic into a blog post, social caption, image alt text, and ready-to-publish content package.', 'n8n', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1owE2sCzZCn_V8KQ6U2GL4X0-t_5F9RFf3nx5nrKuqWM/edit?usp=drivesdk'),
    (3, 4, 'AI Workflow: Content Pipeline', 'Students build an advanced n8n content pipeline that turns a topic into a blog post, social caption, image alt text, and ready-to-publish content package.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1-_kLoq5GCI_YpYFRYKGYEa_plVKR-RxwHMWgEQ76tKI/edit?usp=drivesdk'),
    (3, 4, 'AI Workflow: Content Pipeline', 'Students build an advanced n8n content pipeline that turns a topic into a blog post, social caption, image alt text, and ready-to-publish content package.', 'n8n', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1WUU8WaM-5EUnkXTqeNuAn4BeskSOzQzzCAtGUqplUYc/edit?usp=drivesdk'),
    (3, 5, 'Advanced Automations using Zapier', 'Students create advanced automation workflows using Zapier to connect apps and automate complex multi-step processes.', 'Zapier', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1SKnlu8TDKMPewvdVnRQT-_tplYYa7ptEo6AQfUaSXL8/edit?usp=drivesdk'),
    (3, 5, 'Advanced Automations using Zapier', 'Students create advanced automation workflows using Zapier to connect apps and automate complex multi-step processes.', 'Zapier', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/10jCC84evZJP0xJh9sOH5FhXtyXGoS8uGW5KsL-4Kmxw/edit?usp=drivesdk'),
    (3, 5, 'Advanced Automations using Zapier', 'Students create advanced automation workflows using Zapier to connect apps and automate complex multi-step processes.', 'Zapier', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1JOiM86uUj4KrpzRxNqagus9WDukvBgdZ04McavBVMn8/edit?usp=drivesdk'),
    (3, 5, 'Advanced Automations using Zapier', 'Students create advanced automation workflows using Zapier to connect apps and automate complex multi-step processes.', 'Zapier', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1fWy2UtQgTZpNtBMA8Sr8mkxOoA_DJRObxJlFEcdA-Fo/edit?usp=drivesdk'),
    (3, 6, 'Introduction to ClawBot', 'Students learn ClawBot foundations, including installation, configuration, VPS setup, and launching an automation hub.', 'ClawBot', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/12myH4SU22MmErlJn0IaHe5PelexwGwFqwn9aRMAhL_w/edit?usp=drivesdk'),
    (3, 6, 'Introduction to ClawBot', 'Students learn ClawBot foundations, including installation, configuration, VPS setup, and launching an automation hub.', 'ClawBot', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1e8e-M9GoYm-VMfGJ_ErZLy9xwJ_A2O5gJ5Uv-QOfaQk/edit?usp=drivesdk'),
    (3, 6, 'Introduction to ClawBot', 'Students learn ClawBot foundations, including installation, configuration, VPS setup, and launching an automation hub.', 'ClawBot', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1d7eqInnUpWk284l3iR6VCbxHYPldTA1jXHxSwDkoY9I/edit?usp=drivesdk'),
    (3, 6, 'Introduction to ClawBot', 'Students learn ClawBot foundations, including installation, configuration, VPS setup, and launching an automation hub.', 'ClawBot', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1rgMYM0L_Z3-e7MU3Ict2VwpRlqhW3ST4sbXuIyPs6fU/edit?usp=drivesdk'),
    (3, 7, 'Mastering ClawBot Skills', 'Students implement document and file handling skills, integrate channel connectors, and extend ClawBot with custom skills.', 'ClawBot', 'AI Automation', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1DcXEMl2CW0acd18tdEfr80nVnqPtYOPfNJGCs5XLu2E/edit?usp=drivesdk'),
    (3, 7, 'Mastering ClawBot Skills', 'Students implement document and file handling skills, integrate channel connectors, and extend ClawBot with custom skills.', 'ClawBot', 'AI Automation', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1-BEVoPDSadcg5s5YT9p2WfR_9pPWH0mkim3VpXDmbnA/edit?usp=drivesdk'),
    (3, 7, 'Mastering ClawBot Skills', 'Students implement document and file handling skills, integrate channel connectors, and extend ClawBot with custom skills.', 'ClawBot', 'AI Automation', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1fEtVkgtbCnM2d-KS2_WUMmSLzMjCPifM7TLKn3z-VwM/edit?usp=drivesdk'),
    (3, 7, 'Mastering ClawBot Skills', 'Students implement document and file handling skills, integrate channel connectors, and extend ClawBot with custom skills.', 'ClawBot', 'AI Automation', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/19kOdVivv4JrcppGMXNeHugvI1hUZv_Dk3srqv13icTY/edit?usp=drivesdk'),
    (3, 8, 'Showcase Session - Present Your Smart AI App', 'Students present their final automation projects built throughout the module.', 'ClawBot, Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 1', 'https://docs.google.com/document/d/1UqCxJTurnygdR9iYR87wQtF5NMDZw1jTQ5UEkrQgmSQ/edit?usp=drivesdk'),
    (3, 8, 'Showcase Session - Present Your Smart AI App', 'Students present their final automation projects built throughout the module.', 'ClawBot, Gamma', 'AI Productivity', 'Class Challenge', 'Class Challenge 2', 'https://docs.google.com/document/d/1gQUdOEZmfO9aVcdjuYN6XD9_-kH7CsjWADyU5uVYc-8/edit?usp=drivesdk'),
    (3, 8, 'Showcase Session - Present Your Smart AI App', 'Students present their final automation projects built throughout the module.', 'ClawBot, Gamma', 'AI Productivity', 'Home Task', 'Home Task 1', 'https://docs.google.com/document/d/1_ZwIDPZr8jIGtSJd_rnSiC-xKE-fqQdcW1FVudntd5g/edit?usp=drivesdk'),
    (3, 8, 'Showcase Session - Present Your Smart AI App', 'Students present their final automation projects built throughout the module.', 'ClawBot, Gamma', 'AI Productivity', 'Home Task', 'Home Task 2', 'https://docs.google.com/document/d/1TuqlSumAho69ZM1HOVSUTQbuQOthkDJlnOc8EqfIGbE/edit?usp=drivesdk')
)
insert into public.homework (
  session_id,
  batch_id,
  assigned_student_id,
  title,
  description,
  kind,
  content_url,
  due_date,
  created_at
)
select
  s.id,
  null,
  null,
  'Module ' || c.module_order || ' · Session ' || c.session_number || ': ' || c.session_title || ' — ' || c.file_name,
  case
    when c.resource_type = 'Class Challenge'
      then 'In-class activity for ' || c.session_title || '. Students apply the session concept using ' || c.tools || '. ' || c.what_students_learn
    else 'Homework task for ' || c.session_title || '. Students continue practicing independently using concepts from ' || c.ai_type || '. ' || c.what_students_learn
  end,
  case
    when c.resource_type = 'Class Challenge' then 'class_challenge'::public.homework_kind
    else 'home_task'::public.homework_kind
  end,
  c.google_doc_link,
  date '2026-12-31',
  now()
from coursework c
join public.modules m
  on m.order_index = c.module_order
join public.sessions s
  on s.module_id = m.id
 and s.session_number = c.session_number;

do $$
declare
  inserted_count integer;
begin
  select count(*) into inserted_count from public.homework;
  if inserted_count <> 96 then
    raise exception 'Expected 96 homework rows after coursework reset, found %', inserted_count;
  end if;
end $$;

commit;
